name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t adamwalmsley/ia3-image:${{ env.VERSION }} .
          docker tag adamwalmsley/ia3-image:${{ env.VERSION }} adamwalmsley/ia3-image:latest

      - name: Push Docker images
        run: |
          docker push adamwalmsley/ia3-image:${{ env.VERSION }}
          docker push adamwalmsley/ia3-image:latest
